# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Template.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 390)
        MainWindow.setStyleSheet("QFrame#frame{\n"
#"    background-color: qlineargradient(spread:pad, x1:1.072045, y1:0.124, x2:0.368, y2:1, stop:0.227273 rgba(80, 214, 255, 155), stop:0.806818 rgba(112, 32,213,191));\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.1, x2:0.5, y2:0.3, stop:0.227273 rgba(29, 185, 84, 255), stop:0.606818 rgba(0, 0,0,255));\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#close{\n"
"    background-color: rgba(0, 0,0, 0);\n"
"    color:rgba(0,0,0,255);\n"
"    \n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#close:hover{\n"
"    color:rgba(250,223,11,255);\n"
"}\n"
"#song_name{\n"
"    color:rgba(255,255,255,255);\n"
"}\n"
"#status_label{\n"
"    color:rgba(255,255,255,255);\n"
"}\n"
"#status_msg{\n"
"    color:rgba(255,255,255,255);\n"
"}\n"
"#counter_label{\n"
"    color:rgba(255,255,255,255);\n"
"}\n"
"QPushButton#close:pressed{\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QLineEdit#playlist_link{\n"
"    background-color:rgba(0,0,0,0);\n"
"    border:2px solid rgba(0,0,0,0);\n"
"    border-bottom-color: rgba(100,100,100,255);\n"
"    color:rgb(255,255,255);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"\n"
"QPushButton#Select_Home{\n"
"    background-color: rgba(0, 0,0, 0);\n"
"    color:rgba(200,200,200,255);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#Select_Home:hover{\n"
"    color:rgba(250,223,11,255);\n"
"}\n"
"\n"
"QPushButton#Select_Home:pressed{\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 360, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(0, 13, 260, 41))
        self.title.setMaximumSize(QtCore.QSize(16777204, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("label")
        
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(330, 10, 20, 20))
        self.close.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close.setFont(font)
        self.close.setObjectName("close")
        
        self.playlist_link = QtWidgets.QLineEdit(self.frame)
        self.playlist_link.setGeometry(QtCore.QRect(30, 70, 300, 40))
        font = QtGui.QFont()
        font.setKerning(False)
        self.playlist_link.setFont(font)
        self.playlist_link.setMouseTracking(False)
        self.playlist_link.setAcceptDrops(False)
        self.playlist_link.setWhatsThis("Enter Spotify playlist Link")
        self.playlist_link.setStyleSheet("")
        self.playlist_link.setText("")
        self.playlist_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.playlist_link.setClearButtonEnabled(True)
        self.playlist_link.setObjectName("playlist_link")
        
        self.song_name = QtWidgets.QLabel(self.frame)
        self.song_name.setGeometry(QtCore.QRect(30, 163, 351, 271))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(10)
        self.song_name.setFont(font)
        self.song_name.setText("")
        self.song_name.setWordWrap(True)
        self.song_name.setObjectName("song_name")
        
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 270, 201, 20))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.status_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.status_label.setMinimumSize(QtCore.QSize(40, 0))
        self.status_label.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_3.addWidget(self.status_label)
        self.status_msg = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        
        self.status_msg.setFont(font)
        self.status_msg.setText("")
        self.status_msg.setObjectName("status_msg")
        self.horizontalLayout_3.addWidget(self.status_msg)
        
        self.song_name = QtWidgets.QLabel(self.frame)
        self.song_name.setGeometry(QtCore.QRect(30, 150, 201, 22))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(9)
        self.song_name.setFont(font)
        self.song_name.setWordWrap(True)
        self.song_name.setObjectName("song_name")
        
        self.counter_label = QtWidgets.QLabel(self.frame)
        self.counter_label.setGeometry(QtCore.QRect(30, 240, 201, 22))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(9)
        self.counter_label.setFont(font)
        self.counter_label.setWordWrap(True)
        self.counter_label.setObjectName("counter_label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Spotify Downloader"))
        self.close.setText(_translate("MainWindow", "X"))
        self.playlist_link.setPlaceholderText(_translate("MainWindow", "Enter Spotify Playlist Link"))
        self.status_label.setText(_translate("MainWindow", ""))
        self.song_name.setText(_translate("MainWindow", " "))
        self.counter_label.setText(_translate("MainWindow", ""))
     

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
